# Generated by Django 3.0.5 on 2020-10-15 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(max_length=254)),
                ('post_image', models.ImageField(blank=True, upload_to='article_image')),
                ('article_title', models.TextField(blank=True, max_length=80)),
                ('article_body', models.TextField(blank=True)),
                ('tag', models.CharField(max_length=18)),
                ('post_created', models.DateTimeField(auto_now=True)),
                ('like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
